// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SolidSavings.Web.DataAccess;
using SolidSavings.Web.Models.Enums;
using System;

namespace SolidSavings.Web.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SolidSavings.Web.DataAccess.SolidUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("UserRegistrationType");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SolidSavings.Web.Models.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Month");

                    b.Property<decimal>("Netto");

                    b.Property<Guid>("UserId");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("SolidSavings.Web.Models.Outcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Month");

                    b.Property<decimal>("Netto");

                    b.Property<Guid>("UserId");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Outcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
